### PR TITLE
Added Issue Templates

### PR DESCRIPTION
**Pull request by icebelly29**

### CODE REVIEW

**Comment by AbhijithGanesh** [comment]
@icebelly29 please link relevant issue

**Comment by icebelly29** [comment]
This PR solves issue #1

**Review by AbhijithGanesh — CHANGES_REQUESTED** [review]
We request you to delete the `bug_report.md` and `feature_request.md`

**Comment by icebelly29** [comment]
Please check now

**Review by AbhijithGanesh — APPROVED** [review]
LGTM

**Pull request merged**
